name: s5_msgpack
description: Streaming API implementation of MessagePack binary serialization format - msgpack.
version: 0.3.0
homepage: https://github.com/s5-dev/msgpack
repository: https://github.com/s5-dev/msgpack

environment:
  sdk: ">=2.12.0 <4.0.0"


dev_dependencies:
  test: ^1.16.0
